name: Run kurobako benchmark
on:
  pull_request:
    paths:
    - '.github/workflows/benchmark-ackley.yml'
    - 'internal/**.go'
    - 'tpe/**.go'
jobs:
  benchmarks:
    name: Run kurobako benchmark
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Download kurobako CLI
        run: |
          curl -L https://github.com/sile/kurobako/releases/download/0.1.8/kurobako-0.1.8.linux-amd64 -o kurobako
          chmod +x kurobako
          ./kurobako -h

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud info
      - run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Run sigopt/evalset/Ackley Benchmark
        env:
          KUROBAKO: ./kurobako
        run: |
          ./_benchmarks/run_sigopt_ackley.sh ./kurobako-report.json

      - name: Plot kurobako result
        uses: c-bata/github-actions-kurobako/plot@v1
        id: kurobako-plot
        with:
          report-json-path: './kurobako-report.json'
      - name: Upload an image to google cloud storage
        run: gsutil cp ${{ steps.kurobako-plot.outputs.image-path }} gs://kurobako-reports/${{ github.repository }}/ackley-${{ github.sha }}.png

      - name: Generate kurobako markdown report
        run: |
          cat ./kurobako-report.json | ./kurobako report > ./kurobako-report.md

      - name: Comment to Pull Request
        uses: c-bata/github-actions-kurobako@v2
        with:
          report-md-path: './kurobako-report.md'
          public-image-url: https://storage.googleapis.com/kurobako-reports/${{ github.repository }}/ackley-${{ github.sha }}.png
          title: 'Benchmark result of sigopt/evalset/Ackley problem'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
